### ISSUE TITLE
Enhancement - 20240917

### ISSUE THREAD

**Issue by a1603169** [lovevaro3/practice#2]
## Goal

To make identically exact same page as [Link](https://seunghun-website.vercel.app/).

## Todo (Feedback)

- [ ] From next task, you should create `pull request` by working at a different branch!
- [ ] Color is not the same - Fix this by using color picker
- [ ] Location of navbar contents are not as same as the the link that I provided
- [ ] Fix Font size / Font style 
- [ ] Create Footer (Hint: CSS - focus, active, hover)

### Hint

Use chrome debugger!!!!!!!

**Comment by a1603169** [comment]
## Next Level

- [ ] Make it responsive
